Controllers/EquipmentController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class EquipmentController : Controller
    {

        ShoesStoreDataContextDataContext DataContxt = new ShoesStoreDataContextDataContext();

        public ActionResult ShowAllEquipment()
        {
            List<sportEquipment> Equipment = DataContxt.sportEquipments.ToList();
            ViewBag.Equipment = Equipment;
            return View();
        }

        public ActionResult ShowAllEquipmentInTabel()
        {
            List<sportEquipment> EquipmentTable= DataContxt.sportEquipments.ToList();
            ViewBag.EquipmentTable = EquipmentTable;
            return View();
        }

        public ActionResult ShowOnlyFootball()
        {
            List<sportEquipment> Football = DataContxt.sportEquipments.ToList();
            ViewBag.Football = Football;
            return View();
        }

        public ActionResult ShowOnlyBasketball()
        {
            List<sportEquipment> Basketball = DataContxt.sportEquipments.ToList();
            ViewBag.Basketball = Basketball;
            return View();
        }
        public ActionResult SortByPrice()
        {
            List<sportEquipment> ListEquipment = DataContxt.sportEquipments.OrderBy(item => item.price).ToList();
            ViewBag.Sort = ListEquipment;
            return View();

        }
    }
}

Controllers/ShoesController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ShoesController : Controller
    {
        ShoesStoreDataContextDataContext DataContxt=new ShoesStoreDataContextDataContext();
        public ActionResult ShowAllShoes()
        {
            List<Shoe>Shoes = DataContxt.Shoes.ToList();
            ViewBag.Shoes = Shoes ;
            return View();         
        }

        public ActionResult ShowAllShoesInTable()
        {
            List<Shoe> Shoes = DataContxt.Shoes.ToList();
            ViewBag.Shoes = Shoes;
            return View();
        }
        public ActionResult ShoesOnSale()
        {
            List<Shoe> Sale = DataContxt.Shoes.ToList();
            ViewBag.Sale = Sale;
            return View();
        }


    }
}

Controllers/api/EquipmentController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SportsStore.Controllers.api
{
    public class EquipmentController : ApiController
    {
        ShoesStoreDataContextDataContext DC = new ShoesStoreDataContextDataContext();
        // GET: api/Equipment
        public IHttpActionResult Get()
        {
            try
            {
                List<SportsEquipment> SportsEquipmentList = DC.SportsEquipments.ToList();
                return Ok(new { SportsEquipmentList });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: api/Equipment/5
        public IHttpActionResult Get(int id)
        {
            try
            {
                SportsEquipment OneEquipment = DC.SportsEquipments.First((Item) => Item.Id == id);
                return Ok(new { OneEquipment });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        // POST: api/Equipment
        public IHttpActionResult Post([FromBody] SportsEquipment Equipment)
        {
            try
            {
                DC.SportsEquipments.InsertOnSubmit(Equipment);
                DC.SubmitChanges();
                return Ok("Add");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

        }

        // PUT: api/Equipment/5
        public IHttpActionResult Put(int id, [FromBody] SportsEquipment equipment)
        {
            try
            {
                SportsEquipment EquipmentToUpdate = DC.SportsEquipments.Single(Item => Item.Id == id);
              EquipmentToUpdate = equipment;
                DC.SubmitChanges();
                return Ok("Eddit");

            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // DELETE: api/Equipment/5
        public IHttpActionResult Delete(int id)
        {
            try
            {
                SportsEquipment RemoveEquipment = DC.SportsEquipments.First(Item => Item.Id == id);
                DC.SportsEquipments.DeleteOnSubmit(RemoveEquipment);
                DC.SubmitChanges();
                return Ok("Removed");
            }
            catch (SqlException sqlEx)
            {
                return BadRequest(sqlEx.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

Views/Equipment/ShowAllEquipment.cshtml
<link href="@Url.Content("~/Content/StyleSheet1.css")" rel="stylesheet" type="text/css" />
<div class="containebutton">
    <div class="button">
        <button type="button" onclick="location.href = '@Url.Action("ShowOnlyBasketball", "Equipment") '">Basketball</button>
        <button type="button" onclick="location.href='@Url.Action("ShowOnlyFootball", "Equipment")'">Football</button>
        <button type="button" onclick="location.href='@Url.Action("ShowAllEquipmentInTabel", "Equipment")'">Tabel</button>
        <button type="button" onclick="location.href = '@Url.Action("SortByPrice", "Equipment") '">Sort</button>
    </div>
</div>

<div class="containerOfPages">

    @foreach (var item in @ViewBag.Equipment)
    {

        {

            <div class="card">
                <img class="img" src=" @item.Image" />
                <h5>  @item.Company</h5>
                <div class="contentBx">
                    <div class="size">
                      
                        <h6> @item.price</h6>
                        <h6> @item.Amount</h6>
                        <div class="color">
                            
                        </div>
                    </div>
                </div>
            </div>


        }

    }
</div>

Views/Equipment/ShowAllEquipmentInTabel.cshtml
@using SportsStore.Models;

<link href="@Url.Content("~/Content/StyleSheet2.css")" rel="stylesheet" type="text/css" />
<button type="button" onclick="location.href='@Url.Action("ShoesOnSale", "Shoes")'">Sale</button>

<table style="width:100%">

    <tr>
        <th>SportType</th>
        <th>ProductName</th>
        <th>Company</th>
        <th>Price</th>
        <th>Amount</th>
        <th>Image</th>
    </tr>


 

    @foreach (var item in @ViewBag.EquipmentTable)

    {
        <tr>
            <td>@item.sportType</td>
            <td>@item.Product</td>
            <td>@item.Company</td>
            <td> @item.price</td>
            <td>@item.Amount</td>
            <td>  <img src=" @item.Image" width="50px" height="50px" /> </td>
        </tr>

    }

</table>

Views/Equipment/ShowOnlyBasketball.cshtml
@*<link href="https://fonts.googleapis.com/css2?family=Yuji+Boku&display=swap" rel="stylesheet">*@

<link href="@Url.Content("~/Content/StyleSheet1.css")" rel="stylesheet" type="text/css" />
<div class="containerOfPages">
    @foreach (var item in @ViewBag.Basketball)
    {
        if (@item.sportType == "Basketball")
        {

            <div class="card">
                <img class="img" src=" @item.Image" />
                <h5>  @item.Company</h5>
                <div class="contentBx">
                    <div class="size">
                        <h6> @item.SportType</h6>
                        <h6> @item.Price</h6>
                        
                        <div class="color">

                        </div>
                    </div>
                </div>
            </div>


        }
        else
        {

            <span></span>

        }
    }
</div>

Views/Equipment/ShowOnlyFootball.cshtml
@*<link href="https://fonts.googleapis.com/css2?family=Yuji+Boku&display=swap" rel="stylesheet">*@

<link href="@Url.Content("~/Content/StyleSheet1.css")" rel="stylesheet" type="text/css" />
<div class="containerOfPages">
    @foreach (var item in @ViewBag.Football)
    {
        if (@item.sportType == "Football")
        {

            <div class="card">
                <img class="img" src=" @item.Image" />
                <h5>  @item.Company</h5>
                <div class="contentBx">
                    <div class="size">                 
                        <h6> @item.price</h6>
                        <h6> @item.Amount</h6>
                        <div class="color">

                        </div>
                    </div>
                </div>
            </div>


        }
        else
        {

            <span></span>

        }
    }
</div>

Views/Equipment/SortByPrice.cshtml
<link href="@Url.Content("~/Content/StyleSheet1.css")" rel="stylesheet" type="text/css" />

<div class="containerOfPages">

    @foreach (var item in @ViewBag.Sort)
    {
        <div class="card">
            <img class="img" src=" @item.Image" />
            <h5>  @item.sportType</h5>
            <div class="contentBx">
                <div class="size">                  
                    <h6> @item.Company</h6>
                    <h6> @item.price</h6>                
                    <div class="color">
                    </div>
                </div>
            </div>
        </div>
    }
</div>